modLoader = "javafml"
loaderVersion = "[4,)"
license = "${license}"

[[mods]]
modId = "${modid}"
version = "${mod_version}"
displayName = "${name}"
authors = "${authors}"
description = '''
${description}
'''
logoFile = "icon.png"

[[dependencies."${modid}"]]
modId = "neoforge"
type = "required"
versionRange = "[${neoforge_loader_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies."${modid}"]]
modId = "minecraft"
type = "required"
versionRange = "[${minecraft_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies."${modid}"]]
modId = "architectury"
type = "required"
versionRange = "[${architectury_api_version},)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "ipla.mixins.json"
